### ISSUE TITLE
Typo in the readme example

### ISSUE THREAD

**Issue by typhoon71** [alvarob96/investpy_portfolio#4]
There's a little typo in the readme:

```python3
portfolio.add_stock(stock_aymbol='ELE',
```

should be:

```python3
portfolio.add_stock(stock_symbol='ELE',
```

It's in the front page so I suppose you may care about it.

**Comment by alvarobartt** [comment]
Hi @typhoon71! Thanks a lot, you can fork the repo, update the README and open a Pull Request so that I can merge the changes/improvements you make into the master branch. I can change it too, but since you spotted it, I think it's better that you solve it so as to get credits for contributing. Thank you!

**Comment by typhoon71** [comment]
Done.

**Comment by alvarobartt** [comment]
You need to create the pull request to the master branch, since you created the pull requests into your own fork.

**Comment by typhoon71** [comment]
Now?

**Comment by alvarobartt** [comment]
Steps: `New Pull request` at https://github.com/alvarobartt/pyrtfolio/pulls -> `Compare across forks` -> Select your fork -> Describe all the feature, fixes, etc that you solved within your fork
